{ self, inputs, ... }:
{

  flake.nixosModules.mimosaConfiguration =
    { pkgs, ... }:
    {
      # import any other modules from here
      imports = [
        self.nixosModules.mimosaHardware
        self.nixosModules.audio
        self.nixosModules.cliphist
        self.nixosModules.cursor
        self.nixosModules.docker
        self.nixosModules.firefox
        self.nixosModules.fonts
        self.nixosModules.git
        self.nixosModules.micForward
        self.nixosModules.monitoring
        self.nixosModules.nh
        self.nixosModules.niri
        self.nixosModules.opencode
        self.nixosModules.rofi
        self.nixosModules.shell
        self.nixosModules.singBox
        self.nixosModules.sops
        self.nixosModules.ssh
        self.nixosModules.steam
        self.nixosModules.sunshine
        self.nixosModules.user
        self.nixosModules.vscode
        self.nixosModules.yazi
      ];

      # ==================================================
      # System
      # ==================================================
      nixpkgs.config.allowUnfree = true;

      # mitmproxy root CA (generated by the vrcproxy tool in
      # ~/my-projects/vrcproxy on this host). Trusted system-wide so that
      # Wine/Proton TLS backends verifying against the host bundle accept
      # local HTTPS inspection. Public certificate only - the private key
      # never leaves ~/.mitmproxy on this machine.
      security.pki.certificates = [
        ''
-----BEGIN CERTIFICATE-----
MIIDNTCCAh2gAwIBAgIUJLNA/R1rGnR02hdBM9eK2jYKe3AwDQYJKoZIhvcNAQEL
BQAwKDESMBAGA1UEAwwJbWl0bXByb3h5MRIwEAYDVQQKDAltaXRtcHJveHkwHhcN
MjYwODI0MDAyNjQzWhcNMzYwODIxMDAyNjQzWjAoMRIwEAYDVQQDDAltaXRtcHJv
eHkxEjAQBgNVBAoMCW1pdG1wcm94eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBANUGuxW9DF4dejdYd4vcC+iMUQhfWq7XAiEIqyvZps735sp5jzdH5u54
HTqWXNdB8GjsQGoKrNsUM5ZUl/LPrR/GqPYHi0T46sZDmz7qWareUVqP4azaMMYs
DlvgpM1Emy+UX8slDWNUMHWs0EVOKSshJBfV/urii9twScOdt/c4lruObR7iSkqe
Gsn9DsOhaRnj3lVUTKLMZ6Uur/SyWj9QEfgqgE8yPYWlAqq4BPTA5ufA2KqAveNc
lhH6YWUU1KIt11nEV0Az83ZIWGMPDz/ucjtMhYDS2xP7oOohVkluXuG7kN5CDV+I
Bwon35k80SXUJyDqkbiYbm7bNfZSMfcCAwEAAaNXMFUwDwYDVR0TAQH/BAUwAwEB
/zATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
FNxpH2JIPMnZJCwjTrb5DCp23AmDMA0GCSqGSIb3DQEBCwUAA4IBAQCyBS98bdu8
x6qZ8pa4ydsZ7Ht7LA6ruh7Swu9IUMF6Zn4MA5Z+wqilIpqfGWxkLLCda/R2Bahh
6rtsXIluKqQo9wUVgrcrKdZ0oJz/GL+vyfFkjXibIwQr+XW5b+D3JN/D1WRmUS8c
zbOYrxQTSyTJk2X31uW2TpgXvsx5ixBVI2lTeekzchg4kvWWQoI+AfQFuxBsNOIU
a4EuFeiE4nAa/AlIx52QI17AaDkVijoaJ4y3l3MaSbOaBSlBoMak84aHire02LZr
Q9ipdYCKSZ8d24uqUWYcjzD1r2rA7earEcKDAZYmc+FHVvNNHw12viwjB0C2kg6i
Ho4zRJEIXy8O
-----END CERTIFICATE-----
        ''
      ];

      nix.settings = {
        experimental-features = [
          "nix-command"
          "flakes"
        ];
        auto-optimise-store = true;
      };
      system.stateVersion = "26.05";

      # ==================================================
      # Boot
      # ==================================================
      # Use the systemd-boot EFI boot loader.
      boot.loader.systemd-boot.enable = true;
      boot.loader.efi.canTouchEfiVariables = true;

      # Headless-ready GPU: force-enable HDMI-A-1 and inject a 1920x1080@60
      # mode directly (kernelParams apply at boot — reboot to change). A
      # drm.edid_firmware reference is deliberately NOT used: nixpkgs kernels
      # do not ship the edid/*.bin blobs, and the failed load falls back to
      # the kernel's built-in stub EDID offering only 640x480. With a real
      # monitor attached its native EDID still takes precedence.
      boot.kernelParams = [
        "video=HDMI-A-1:1920x1080@60e"
      ];

      # ==================================================
      # Networking
      # ==================================================
      networking.hostName = "mimosa"; # Define your hostname.
      networking.networkmanager.enable = true; # Easiest to use and most distros use this by default.

      # Set your time zone.
      time.timeZone = "Europe/Moscow";

      # Firewall: server exposes SSH only.
      networking.firewall = {
        enable = true;
        allowedTCPPorts = [ 22 ];
      };

      # ==================================================
      # Users
      # ==================================================
      # Primary account, consumed by the user/git features.
      myUser = {
        name = "mimosa";
        fullName = "Ioplock";
        email = "ioplock.me@gmail.com";
        # input group grants write access to /dev/uinput for Sunshine's
        # virtual gamepads and other input injection.
        extraGroups = [
          "wheel"
          "input"
        ];
        authorizedKeys = [
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO2reTQCZyP5XULzWNsQ0iVGxwYylpkW8xuK1hG+DaE9 ioplock.me@gmail.com"
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGmxqTkkihZlO5FEriD9Xxp8do+3GbVxR7xsa9V/aHGE daniiilbackto2007@gmail.com"
        ];
      };

      programs.nh.flake = "/home/mimosa/nixconf";

      # ==================================================
      # Desktop (gaming niri: compact status bar — clock, layout, volume,
      # workspace, focused window, settings; no wifi/bluetooth/battery)
      # ==================================================
      myNiri.package = self.packages.${pkgs.stdenv.hostPlatform.system}.myNiriGaming;

      # ==================================================
      # Mic forwarding (Sunshine host)
      # ==================================================
      # Expose a virtual mic that clients (acrux, Windows PCs) stream into
      # while a Sunshine session is live, so games hear you talk.
      myMicForward = {
        enableReceiver = true;
        enableVbanReceiver = true; # VoiceMeeter/VBAN mic from Windows clients
      };

      # ==================================================
      # Video
      # ==================================================
      hardware.graphics = {
        enable = true;
        enable32Bit = true; # Required by Steam/Wine 32-bit games.
      };

      # ==================================================
      # SSH
      # ==================================================
      # Key-only login.
      services.openssh.settings.PasswordAuthentication = false;

      # ==================================================
      # Monitoring
      # ==================================================
      # Netdata UI reachable from the LAN on :19999 (smartd included).
      myMonitoring = {
        enable = true;
        openFirewall = true;
      };
    };

}
