{ self, inputs, ... }:
{
  flake.nixosModules.mimosaHardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      # Do not modify this file!  It was generated by ‘nixos-generate-config’
      # and may be overwritten by future invocations.  Please make changes
      # to /etc/nixos/configuration.nix instead.
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/5d40635f-384a-44c2-b0b8-8325b793d242";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/49A1-C773";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      fileSystems."/mnt/disk0" = {
        device = "/dev/disk/by-uuid/b0aa79da-5479-4647-beca-6ec5c7ed46e0";
        fsType = "ext4";
      };

      fileSystems."/mnt/disk1" = {
        device = "/dev/disk/by-uuid/55337869-308b-49cc-90ad-e2acb6186664";
        fsType = "ext4";
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/70725dbc-8205-43b1-ab0b-9bd1afb9a849"; }
      ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };

}
