{ self, inputs, ... }:
{
  flake.nixosModules.sunshine =
    { config, pkgs, lib, ... }:
    let
      # Same rendering the upstream module performs for settings; needed here
      # because the singleton launcher below has to be invoked with the
      # config-file argument by the unit.
      confFile = (pkgs.formats.keyValue { }).generate "sunshine.conf"
        config.services.sunshine.settings;

      # Singleton launcher used by EVERYTHING (unit and manual runs): a second
      # invocation exits instantly instead of racing for ports or corrupting
      # state. The lock holder execs the CAP_SYS_ADMIN ELF wrapper so KMS
      # capture keeps working — a shell script cannot carry file capabilities,
      # hence the separate sunshine-real wrapper below.
      guarded =
        (pkgs.writeShellScriptBin "sunshine" ''
          ${pkgs.util-linux}/bin/flock -n /tmp/sunshine.lock true || \
            { echo "sunshine: already running (systemd user service)" >&2; exit 1; }
          exec ${pkgs.util-linux}/bin/flock /tmp/sunshine.lock \
            ${config.security.wrapperDir}/sunshine-real "$@"
        '').overrideAttrs (_: { meta.mainProgram = "sunshine"; });
    in
    {
      services.sunshine = {
        enable = true;
        package = guarded;
        autoStart = true;
        # Upstream's capSysAdmin would wrap getExe(package) — our script — and
        # setcap cannot apply to scripts. The equivalent capability lives on
        # sunshine-real below instead.
        capSysAdmin = false;
        openFirewall = true;

        settings = {
          # Exactly two keys: the NixOS module only passes the rendered config
          # file when more than one setting differs from defaults, and any
          # settings at all lock out web-UI configuration (declarative mode).
          sunshine_name = "mimosa";
          # Immutable flat JSON {username,password,salt}; BOTH password hash
          # and salt MUST be generated by the sunshine binary itself (see
          # docs/remote-gaming.md — the hashing scheme is version-specific).
          # Pairing state lives separately in ~/.config/sunshine/sunshine_state.json.
          credentials_file = config.sops.secrets.sunshine-credentials.path;
        };
      };

      # The capability-carrying entry point (real ELF binary).
      security.wrappers.sunshine-real = {
        source = "${pkgs.sunshine}/bin/sunshine";
        owner = "root";
        group = "root";
        capabilities = "cap_sys_admin+p";
      };

      # Upstream points udev at cfg.package (now the script, which ships no
      # rules); keep the real package's gamepad/input rules loaded.
      services.udev.packages = [ pkgs.sunshine ];

      # Replace the upstream argument list wholesale: same rendered config,
      # but through the singleton launcher.
      systemd.user.services.sunshine.serviceConfig.ExecStart =
        lib.mkForce "${guarded}/bin/sunshine ${confFile}";
    };
}
