{ self, inputs, ... }:
{
  flake.nixosModules.sunshine =
    { config, pkgs, lib, ... }:
    let
      # Same rendering the upstream module performs for settings; needed here
      # because the singleton guard below has to rebuild ExecStart with the
      # config-file argument included.
      confFile = (pkgs.formats.keyValue { }).generate "sunshine.conf"
        config.services.sunshine.settings;

      # Singleton guard around the setcap wrapper: a second invocation
      # (manual terminal launch, rofi entry, stray autostart) exits instantly
      # instead of racing the systemd user service for ports. flock execs the
      # CAP_SYS_ADMIN wrapper directly, so file capabilities survive the chain.
      guarded = pkgs.writeShellScript "sunshine-singleton" ''
        ${pkgs.util-linux}/bin/flock -n /tmp/sunshine.lock true || \
          { echo "sunshine: already running (systemd user service)" >&2; exit 1; }
        exec ${pkgs.util-linux}/bin/flock /tmp/sunshine.lock \
          ${config.security.wrapperDir}/sunshine ${confFile}
      '';
    in
    {
      # Upstream module: systemd *user* service bound to graphical-session.target,
      # which uwsm activates for the greetd autologin niri session.
      services.sunshine = {
        enable = true;
        autoStart = true;
        # KMS capture headroom via setcap on the real ELF binary; Wayland
        # capture is used inside the session either way. Headless works thanks
        # to the forced-EDID kernel params.
        capSysAdmin = true;
        openFirewall = true;

        settings = {
          # Exactly two keys: the NixOS module only passes the rendered config
          # file when more than one setting differs from defaults, and any
          # settings at all lock out web-UI configuration (declarative mode).
          sunshine_name = "mimosa";
          # Immutable flat JSON {username,password,salt}; BOTH password hash
          # and salt MUST be generated by the sunshine binary itself (see
          # docs/remote-gaming.md — the hashing scheme is version-specific).
          # Pairing state lives separately in ~/.config/sunshine/sunshine_state.json.
          credentials_file = config.sops.secrets.sunshine-credentials.path;
        };
      };

      # Replace the plain ExecStart with the guarded one. mkForce is safe: the
      # upstream argument list is fully reconstructed above (wrapper + config).
      systemd.user.services.sunshine.serviceConfig.ExecStart =
        lib.mkForce "${guarded}";
    };
}
