{ self, inputs, ... }:
{
  perSystem =
    { pkgs, ... }:
    {
      # Sunshine wrapped with a singleton lock: a second invocation (manual
      # terminal launch, rofi entry, stray autostart) exits immediately
      # instead of racing the systemd user service for ports.
      #
      # The shim is a shell script, so this package must NOT be given file
      # capabilities (setcap cannot carry over interpreters) — hence
      # capSysAdmin = false below. Capture runs through the Wayland protocol
      # inside the autologin session, which works headless thanks to the
      # forced-EDID kernel params.
      packages.mySunshine =
        let
          real = "${pkgs.sunshine}/bin/sunshine";
        in
        pkgs.symlinkJoin {
          name = "sunshine-${pkgs.sunshine.version}-singleton";
          paths = [ pkgs.sunshine ];
          meta.mainProgram = "sunshine";
          postBuild = ''
            rm $out/bin/sunshine
            cat > $out/bin/sunshine <<'EOF'
            #!/bin/sh
            ${pkgs.util-linux}/bin/flock -n /tmp/sunshine.lock true || \
              { echo "sunshine: already running (systemd user service)" >&2; exit 1; }
            exec ${pkgs.util-linux}/bin/flock /tmp/sunshine.lock ${real} "$@"
            EOF
            chmod +x $out/bin/sunshine
          '';
        };
    };

  flake.nixosModules.sunshine =
    { config, pkgs, ... }:
    {
      # Upstream module: systemd *user* service bound to graphical-session.target,
      # which uwsm activates for the greetd autologin niri session.
      services.sunshine = {
        enable = true;
        package = self.packages.${pkgs.stdenv.hostPlatform.system}.mySunshine;
        autoStart = true;
        openFirewall = true;

        settings = {
          # Exactly two keys: the NixOS module only passes the rendered config
          # file when more than one setting differs from defaults, and any
          # settings at all lock out web-UI configuration (declarative mode).
          sunshine_name = "mimosa";
          # Immutable flat JSON {username,password,salt}; BOTH password hash
          # and salt MUST be generated by the sunshine binary itself (see
          # docs/remote-gaming.md — the hashing scheme is version-specific).
          # Pairing state lives separately in ~/.config/sunshine/sunshine_state.json.
          credentials_file = config.sops.secrets.sunshine-credentials.path;
        };
      };
    };
}
